# Generated by Django 5.1 on 2024-08-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='video',
            name='unlikes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
